# -*- coding: utf-8 -*-
"""Worked-example enrichment for the DaVinci Basics memo, keyed by question num."""

EXAMPLES = {
 1: "Open Resolve and look along the bottom bar — you'll count seven icons: Media, Cut, Edit, Fusion, Color, Fairlight, Deliver, each a full workspace.",
 2: "If a tutorial says 'go to the Compose page,' it's wrong — that compositing work actually happens on the Fusion page.",
 3: "Finishing a wedding film: cut on Edit, grade on Color, mix on Fairlight, then switch to Deliver last to render the MP4 you hand the client.",
 4: "A YouTuber can monetise videos cut entirely in the free version; you'd only buy Studio when you need Magic Mask, noise reduction or HDR.",
 5: "To send a project to a collaborator, right-click it in the Project Manager → Export Project → it saves a single .drp file you can email.",
 6: "Launch Resolve cold and you land in the Project Manager — a grid of project thumbnails — before any editing UI appears.",
 7: "Glance at the very bottom of the window: that row of seven page icons is how you move between workspaces.",
 8: "The icons read left-to-right as Media → Cut → Edit → Fusion → Color → Fairlight → Deliver — the same order you actually work in.",
 9: "Mid-project you click the small house icon top-left to pop back to the Project Manager and open a different job.",
 10: "Editing on a laptop, you tap the panel toggle to hide the Media Pool and Inspector so the viewer fills the screen.",
 11: "Force-quit Resolve after a crash and on relaunch your timeline is intact, because Live Save wrote every change as you worked.",
 12: "A typical short: import clips (Media) → build the cut (Edit) → grade it (Color) → export (Deliver).",
 13: "Delete a clip from the Media Pool and the file still sits on your drive — the Pool only tracked a reference to it.",
 14: "You browse an external SSD in Media Storage, then drag the folder you want into the Media Pool to actually register those clips in the project.",
 15: "Drag your 'Day 1' and 'Day 2' camera folders onto the bin list and Resolve recreates that same bin structure automatically.",
 16: "Set a Smart Bin rule 'Keyword contains interview' and every interview clip — wherever it lives — shows up there automatically.",
 17: "A clip imported as stereo but it's really a mono lav: right-click → Clip Attributes → Audio to set it to mono.",
 18: "Boom on a Zoom, scratch audio on-camera: select both, right-click → Auto-Sync Audio → Synchronize using Waveform, and Resolve lines them up by the clap.",
 19: "Put your studio logo and sound-effects library in a Power Bin and they're available in every project you open — no re-import.",
 20: "On the Media page the clip you double-click previews in the top-right Source Viewer while the Pool sits in the centre.",
 21: "Click the little list/thumbnail icons at the top of the Media Pool to switch from big thumbnails to a sortable List view.",
 22: "Your project's bin folders run down the left edge of the Media Pool.",
 23: "A 29.97 clip races in your 23.976 timeline — right-click → Clip Attributes → Video → set 23.976 and it plays correctly, no re-render.",
 24: "Cutting a drama, you sort the Pool by Scene then Take to find 'Scene 4, Take 3 (circle take)' in seconds.",
 25: "The Edit page shows the Source Viewer (left) for raw clips and the Timeline Viewer (right) for your cut, side by side.",
 26: "You scrub a 10-minute interview in the Source Viewer, set in/out, then drop only that chunk into the timeline.",
 27: "Select a title and the Inspector (top-right) fills with its font, size and position controls.",
 28: "Need a cross-dissolve? Click Effects at the top-left, then drag the transition onto your cut.",
 29: "Open the Edit Index to see a numbered, spreadsheet-style list of every cut — handy for jumping to edit #42 or exporting an EDL.",
 30: "Press A to get the arrow back after using the blade, so you can grab and move clips again.",
 31: "Press B and click a clip to slice it exactly where you want to remove a cough.",
 32: "Press T and drag the upper half of a clip to slip it — changing what's shown without moving its position.",
 33: "Park the playhead on a flub and press Cmd/Ctrl+\\ to split the clip there so you can delete the bad part.",
 34: "With Snapping on, a dragged clip jumps to butt cleanly against the previous clip's end instead of leaving a one-frame gap.",
 35: "Drop a missing reaction shot mid-scene with Insert and everything after it slides right to make room.",
 36: "Paint three seconds of B-roll over a shot with Overwrite — it covers without changing the timeline's length.",
 37: "Scrub to where the good take begins and press I to set the In point.",
 38: "Scrub to the end of the line and press O to set the Out point before editing it in.",
 39: "Hold L to play forward; tap it again and playback jumps to 2× for fast review — K stops, J runs it backward.",
 40: "With Linked Selection on, clicking the video also grabs its attached audio, so they move together and stay in sync.",
 41: "Select a clip, open Inspector → Transform, click the diamond next to Position to start a push-in animation.",
 42: "Hover the top-left corner of a clip, grab the white triangle and drag right for an instant one-second fade-in.",
 43: "On the Cut page the top strip shows your whole 20-minute project while the bottom shows the few seconds around the playhead — no zooming.",
 44: "Select a bin and hit Source Tape to scrub all 60 clips as one continuous reel, marking keepers as you go.",
 45: "Three-camera interview: Sync Bin auto-aligns the cameras by audio, then you cut between angles just by clicking the one you want at the playhead.",
 46: "On the Cut page Smart Insert drops your clip at the nearest cut, so you don't have to nudge the playhead onto the exact frame.",
 47: "A daily vlog or news package gets cut on the Cut page, where speed beats frame-perfect precision.",
 48: "The DaVinci Speed Editor's jog wheel and source buttons are built around the Cut page for fast assembly.",
 49: "Finish a social clip on Cut, hit Quick Export top-right, pick YouTube, and it renders without opening Deliver.",
 50: "Cut a scene on the Cut page, switch to Edit, and it's the same timeline — your edits are right there, no import.",
 51: "The Cut's upper timeline is the whole project zoomed out; the lower one is the detail — same edit, two zoom levels.",
 52: "Click the Edit icon in the bottom bar to leave Cut and keep working on the identical timeline.",
 53: "Fusion swaps the timeline for a node graph — boxes wired together, each doing one job, like a flowchart.",
 54: "Enter Fusion and you see MediaIn (your clip arriving) wired to MediaOut (the result going back to the timeline).",
 55: "To put a logo over footage you add a Merge: background plate in yellow, logo in green, and it composites them.",
 56: "On a Merge, the sky plate goes in the yellow (background) input and the bird element in green (foreground); blue takes a mask if needed.",
 57: "Click a Blur node and its strength slider appears in the Inspector on the right.",
 58: "Load your final MediaOut in the right viewer and the node you're tweaking in the left, to compare as you work.",
 59: "Select a node and press 1 to throw it into the left viewer for inspection.",
 60: "Press Shift+Spacebar, type 'blur', hit enter — the Blur node drops straight into your graph.",
 61: "Your text snaps to a halt; open the Spline editor and ease the keyframe so it glides to a stop instead.",
 62: "Drag a FastNoise generator from the top-left Effects Library into the node graph.",
 63: "The Fusion node graph fills the bottom half of the page; the viewers sit above it.",
 64: "Track the moving car's number plate, then attach a blur to the tracker so it follows and hides the plate.",
 65: "Move the playhead onto shot 12 and the wheels now grade shot 12 — no selecting required.",
 66: "Your clip's nodes sit in the top-right; pressing Alt+S there adds another correction in series.",
 67: "Open the bottom-right scopes panel and switch to Parade to check your whites are neutral.",
 68: "Point the Parade at a grey wall — if the red channel sits higher than green and blue, the shot is too warm.",
 69: "Turn on the skin-tone line on the Vectorscope and nudge the grade until the face cluster sits along that 11 o'clock line.",
 70: "Pull Lift down to deepen the blacks, push Gamma up to brighten faces, ride Gain to set the highlights.",
 71: "Drag the Gain ring right and the bright sky lifts while the shadows barely move.",
 72: "Drag the Lift centre dot toward teal to push a cool tint into the shadows.",
 73: "Qualify the sky's blue with the Qualifier picker, then desaturate only the sky without touching the rest of the frame.",
 74: "Draw a circular Power Window over the face and brighten only inside it to draw the eye.",
 75: "Grab a still of your hero shot into the top-left Gallery, then wipe it against other shots to match them.",
 76: "Press Alt+S to add a fresh serial node so your vignette sits after your colour balance.",
 77: "Click the '1' on a node to switch your grade off and on and confirm it's actually improving the shot.",
 78: "Select the ungraded shot, hover the graded shot's thumbnail and middle-click — the whole grade copies across instantly.",
 79: "On Fairlight the channel strips with faders run down the right in the Mixer.",
 80: "Double-click the cyan strip on the dialogue channel to high-pass out the low rumble.",
 81: "Click the green strip to drop a compressor on the voice and even out the loud and soft words.",
 82: "Every track feeds Bus 1 by default — that's the stereo mix that actually reaches your speakers and the export.",
 83: "Hit M on the music track header to mute it, or use the same button on its channel strip in the Mixer.",
 84: "The track's name, arm and mute buttons sit on the header at the left edge of each Fairlight track.",
 85: "Set the fader to 0 dB for unity (no change), or pull it to -6 dB to bring the music down under the voice.",
 86: "Aim dialogue peaks into the yellow; if the meter flashes red you're clipping and must pull the level down.",
 87: "Click the red arm button on a track, then record your voiceover straight onto it.",
 88: "Route all five dialogue tracks to a Dialogue Bus so one fader and one EQ control the whole voice mix.",
 89: "Instead of EQ-ing six dialogue tracks one by one, send them to a sub-bus and EQ it once.",
 90: "Drop a De-Esser then a Reverb into the channel's Effects rack to chain them on that voice.",
 91: "Each job you add stacks up in the Render Queue on the right, ready for Render All.",
 92: "Pick your codec and resolution in the Render Settings panel at the top-left before adding the job.",
 93: "Choose .mov as the Format (container) and ProRes as the Codec (encoder) — an MP4 would usually carry H.264 instead.",
 94: "Master to ProRes 4444 so that when the client wants a re-edit in three years it opens pristine in any NLE.",
 95: "Mark I and O around a 30-second teaser and choose 'In to Out' to render just that section.",
 96: "Batch-transcode a card of camera files to ProRes by ticking Individual Clips — one output file per clip.",
 97: "Set up three deliverables, Add each to the Render Queue, then Render All overnight.",
 98: "Click Browse to point the render at your 'Exports' folder and name the file.",
 99: "Start from the YouTube preset, then switch to Custom to bump the bitrate higher.",
 100: "Open the Audio tab in Render Settings to export Linear PCM 24-bit instead of the default AAC.",
}
