# -*- coding: utf-8 -*-
"""Worked-example enrichment for the DaVinci Advanced memo, keyed by question num."""

EXAMPLES = {
 1: "It's like being a fluent Premiere editor handed a tight deadline — you deliver in the tool you already know and learn Resolve on next month's lower-stakes personal short.",
 2: "Drop that H.265 multicam onto a slow spinning drive and scrubbing stutters; move the same files to an NVMe SSD and they scrub instantly — the GPU never changed.",
 3: "An agency can bill a client for a national ad cut entirely in free Resolve — no watermark, no licence fee, fully legal.",
 4: "The client's .drp sits on your desktop doing nothing until you open Project Manager → right-click → Import Project — then it appears in your library and opens.",
 5: "You hand the colourist a drive with the .drp plus the footage folder; they import the project and, if paths differ, Relink finds the media in one pass.",
 6: "Drop the client's 'Cam A / Cam B / Audio' folders onto the bin list and those three bins appear instantly, each holding its clips.",
 7: "You can see a 2 TB archive drive in Media Storage, but until you drag clips into the Pool the project knows nothing about them.",
 8: "Select all 18 ceremony angles plus the Zoom file, right-click → Auto-Sync Audio, and Resolve swaps the tinny camera sound for the clean recorder track across all of them at once.",
 9: "The five that failed were recorded after you'd stopped the Zoom — there's no matching waveform to lock onto, so you sync those by hand on a transient.",
 10: "Tag OTS clips as you log and the 'OTS' Smart Bin fills itself — by the end of day 12 every over-the-shoulder shot is one click away, wherever it lives.",
 11: "You hand the director a watchable start-to-finish assembly from the master takes; they react to the story's shape, not to unfinished colour or transitions.",
 12: "Insert a missing pickup line mid-scene and every later clip slides right to make room — nothing gets painted over.",
 13: "Press S at the start of the dead pause, S at the end, select the middle and delete — the 12 seconds vanish and the two halves ripple together.",
 14: "Grab the lower half of a B-roll clip in the Trim tool and drag — it moves later in time while trimming the clips on either side to fit.",
 15: "The wide ends as she stands; the close-up starts mid-stand — cut on that rising motion and the eye never notices the change of angle.",
 16: "With Q, W and S under your left hand you top-and-tail a podcast clip in two keystrokes, never reaching for the mouse.",
 17: "Your lower-third slides in then slams to a halt — flatten the end keyframe's tangent in the curve view and it glides smoothly to rest.",
 18: "Alt-drag your animated logo to copy it and the copy already pushes in identically — no re-keyframing needed.",
 19: "With the magnet on, the clip you drag clicks neatly onto the previous clip's tail and the playhead, never leaving a stray frame.",
 20: "On Cut you click the top overview to jump to minute 14 of a 20-minute talk while the lower timeline shows the exact frames there — no zooming.",
 21: "Spine the wide of your 4-camera podcast, then click the close-up in the Sync Bin whenever someone speaks and that angle drops straight in.",
 22: "On Cut you don't fuss over the exact frame — Insert lands the clip at the nearest cut and you keep moving at speed.",
 23: "Camera C's on-board mic was almost silent, so auto-sync misplaced it by two seconds — you line it up by hand on the clap.",
 24: "Open a shot in Fusion and you're handed MediaIn (the clip) wired to MediaOut (back to the timeline); you build the composite between them.",
 25: "Sky plate into the Merge's yellow input, the comped bird into green — the bird now sits over the sky.",
 26: "Your roto mask wobbles between frame 1 and frame 30 — right-click in the Inspector → Remove Polyline and the shape freezes.",
 27: "FastNoise makes the clouds, a Polygon limits them to a diagonal streak, and a Merge lays them over the sky — localised smoke, nothing global.",
 28: "Select the Blur node and press 1 to inspect it in the left viewer while your finished MediaOut stays in viewer 2.",
 29: "The alien plate is 4K and the cockpit 1080 — a Transform node shrinks just the alien to fit the cockpit window.",
 30: "Keyframe the noise's Center from left to right and the smoke drifts across the frame; animating Seethe instead would only make it boil in place.",
 31: "Track the actor's eye, set the Merge to Match Move, and the floating UI graphic rides along with every glance.",
 32: "Park the playhead on shot 7 and the wheels grade shot 7; slide to shot 8 and you're now grading that — no selecting.",
 33: "Drag the Gain ring right and the bright sky lifts toward white while the shadows barely move; pull it left to recover a blown window.",
 34: "Lift the top of the curve and dip the bottom — blacks deepen, highlights pop, and the flat log shot suddenly has filmic snap.",
 35: "On the grey wall the red trace towers over green and blue — pull Offset toward cyan until the three level out and the warm cast is gone.",
 36: "Skin sits low at 8 o'clock — nudge it back up the 11 o'clock line via the Main Object node, unless you're deliberately going stylised.",
 37: "Grade shot 1, select shot 2, hover shot 1's thumbnail and middle-click — shot 2 inherits the whole grade instantly.",
 38: "Add the teal-orange look on a timeline node and all 80 clips get it at once, while each clip's own nodes still balance underneath.",
 39: "The compressor pulls the loud words down but the track now sits lower overall — push makeup gain to +6 dB and the dialogue jumps forward.",
 40: "Roll the highs off the off-screen voice and drop it a few dB and it instantly sounds like it's coming through the closed door.",
 41: "The lav landed on the left channel only — Clip Attributes → mono, then Change Track Type → Mono, and it plays evenly in both ears.",
 42: "Send all five body-drop effects to one Bus and a single compressor plus reverb on that Bus glues them together with one set of controls.",
 43: "Click the green strip on the voice channel and the Dynamics panel opens, ready to even out the performance.",
 44: "Find a matching beat at 0:08 and 0:18, blade both points, butt them together with a short crossfade — the 30-second track is now a seamless 20.",
 45: "Drag across the noisy gap in a clip with Range mode and pull its volume to nothing — no splitting, no extra clips left behind.",
 46: "You master the documentary to ProRes 4444; three years later the client reopens it for a recut and it's still pristine and fully gradeable.",
 47: "Set the 1080p timeline to render at UHD and after YouTube re-encodes it the upload looks visibly crisper than a native 1080 export would.",
 48: "The client asks for 'an MP4' — you give them an H.264-in-MP4 file that plays on any phone, laptop or website.",
 49: "The laptop hit 98°C mid-render and scattered white blocks through the file — render again on a cooling stand and it comes out clean.",
 50: "Your captions vanished from the export until you set Subtitle → Burn into video on the Deliver page.",
 51: "Add the YouTube, client-preview and ProRes jobs to the Render Queue, hit Render All before bed, and wake to three finished files.",
 52: "You export the master as Linear PCM 24-bit with all timeline tracks, so a future editor can re-balance dialogue and music separately.",
 53: "Your FX6 log clip looks washed-out grey straight off the card — that flatness is holding the full dynamic range for you to grade back in.",
 54: "Set the working space to DaVinci Wide Gamut Intermediate and your Sony, Canon and iPhone clips all grade in one consistent, future-proof space.",
 55: "Grade on a Mac with Output set to Rec.709-A and the result in QuickTime and Safari matches exactly what you saw in the viewer.",
 56: "Tag the A7S III clips as S-Gamut3.Cine / S-Log3 and the grey log instantly springs to a natural, balanced starting image.",
 57: "The client's standard iPhone clips already look punchy — tag them Rec.709 Gamma 2.4 (effectively a bypass) and grade lightly.",
 58: "You neutralise exposure (Balance), separate skin from background (Isolate), then add the mood (Look) — technical groundwork before any art.",
 59: "Your contrast node feeds the vignette node feeds the grain node — each builds on the last, so changing the order changes the result.",
 60: "Three Global tweaks each start from the same balanced image and sum together, so none of them degrades the others' precision.",
 61: "Stack Background, then Second Object, then Main Object at the bottom — skin overrides everything above it, like the top layer in Photoshop.",
 62: "Because skin sits on the bottom branch, pushing the background blue leaves the face completely untouched.",
 63: "The Parade bunches in the bottom third — push Gain to lift the brights toward 1023, then open the midtones with Gamma.",
 64: "A flat ceiling at 1023 means the sky's detail is already gone — pulling Gain down won't recover it; you'd have had to expose lower on set.",
 65: "The skin looks blotchy and dark — add gentle contrast with the pivot pulled left and the blacks firm up without crushing the face.",
 66: "You add just enough saturation that the qualifier can tell skin from the green wall behind it — the bold colour comes later in the Look.",
 67: "The candle-lit scene is meant to glow amber — you leave the warmth alone because it's the scene's identity, not a white-balance error.",
 68: "You pick the blue sky by hue, tighten the saturation and luminance ranges, and now you can darken only the sky.",
 69: "The 8-bit phone skin matte breaks up — crank Denoise and Blur Radius and box it in with a face window, and it cleans right up.",
 70: "Qualify all skin tones, then drop a circle around the face so background skin-coloured props don't get caught in the selection.",
 71: "The face walks across frame — hit Track Forward and Reverse on the window's Tracker tab and the correction follows automatically.",
 72: "In Studio you stroke the walking subject once and Magic Mask rotos them across the whole shot — no polygon drawn by hand.",
 73: "Push the background cool and the isolated skin on the bottom branch stays exactly as you graded it.",
 74: "Switch on the skin indicator and steer the face cluster onto that 11 o'clock line for natural-looking skin.",
 75: "You park on the best-lit wide of the protagonist and build the whole look there, then carry it across every other shot.",
 76: "An S in the curve — top up, bottom down — gives the digital footage that film-print contrast in a single move.",
 77: "You wipe a still from a film you admire against your shot to give your eye a target — not to copy it pixel-for-pixel.",
 78: "A touch of teal in the shadows and warmth in the highlights gives the blockbuster feel; pushed hard it just screams 'filter.'",
 79: "The look tinted the face green — you nudge skin back on the Main Object node without disturbing the rest of the grade.",
 80: "The Color Slicer's HSV saturation richens colour without lifting brightness, so the grade gets punchier without going milky.",
 81: "All your Global moves draw from the same source and sum, so eight adjustments don't stack up precision errors.",
 82: "Draw a soft circle, invert the key, pull the offset down — the edges darken and the eye falls on the centre of frame.",
 83: "Lift the subject's face a touch with a window and the viewer's eye goes straight to them — the oldest trick in cinematography.",
 84: "Smoothing at 0.4 with Scaling low softens blemishes but keeps the pores, so the actor looks rested rather than plastic.",
 85: "You click the one off-colour jacket on the Warper's grid and drag its hue without disturbing the skin tone right next to it.",
 86: "The head turns and the window drifts off the face — auto-track it and the grade stays locked on.",
 87: "After the Global Look you add a serial Final Look node and pull the whole frame a touch darker and cooler for the night feel.",
 88: "You dial grain down in the shadows so the blacks stay clean while the midtones keep their film texture.",
 89: "No Studio? Drop a grain video on the track above the edit and set its composite mode to Overlay — instant texture, for free.",
 90: "Nudge the Blur radius to 0.46 to sharpen the eyes; push it past 0.5 and it would soften the image instead.",
 91: "Push Sharpen's Scaling toward 1.0 and the eyes and lips snap into detail that survives Instagram's compression.",
 92: "The default-iPhone clip is already display-ready, so the CST is Rec.709 in / Rec.709 out — effectively a bypass.",
 93: "Push the phone sky hard and it bands into visible steps — the 8-bit file simply has no more data to give.",
 94: "One Offset nudge warms the cold office iPhone footage and it instantly looks ten times better — the highest-value phone fix.",
 95: "The iPhone 15 Pro's Apple Log grades like a proper mirrorless camera — tag it Apple Log and use the full node tree.",
 96: "The over-cooked stock clip gets its saturation pulled back toward neutral before you add your look, or you'd be grading on top of someone else's grade.",
 97: "You cut the 16:9 master, grade it once, duplicate-and-reframe for the vertical, mix once, then queue all three renders — no work repeated.",
 98: "The 4K H.265 stutters, so you generate optimised media — playback turns silky and the final render still pulls from the original files.",
 99: "You ask whether the protagonist's warm iPhone look is 'him' or a mistake; deciding it's character, you warm your studio shots to match rather than cooling his.",
 100: "The bold look exposes the second shot's flatter exposure — fix its balance to match the hero's starting point and the same look suddenly fits.",
}
